name: openapi_infrastructure
description: A shared package for openapi clients to use that provides helpful abstractions.
version: 1.0.0
repository: https://github.com/Bdaya-Dev/dart_openapi_infrastructure

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  http_parser: ^4.1.0
  meta: ^1.15.0
dev_dependencies:
  collection: ^1.19.0
  lints: ^3.0.0
  test: ^1.24.0
  cross_file: ^0.3.4+1
